title: "Furniture World"
description: "A curated blog about timeless furniture styles."
url: "https://mrsuntanlotionbottle.github.io/funitureworld"
baseurl: "/funitureworld"  # Remove this if using a user site
author:
  name: "Tom Gillam"
  email: "tom.gillam@yahoo.com"
  github: "mrsuntanlotionbottle"
remote_theme: "mmistakes/so-simple-theme"

paginate: 5  # Number of posts per page

